# This is a basic workflow to help you get started with Actions

name: Packer

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    paths:
      - 'packer/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  packer:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer/packer.pkr.hcl
        env:
          PKR_VAR_aws_region: ${{ secrets.AWS_REGION }}
          PKR_VAR_vpc_id: ${{ secrets.VPC_ID }}
          PKR_VAR_subnet_id: ${{ secrets.SUBNET_ID }}
          PKR_VAR_AKID: ${{ secrets.PACKER_IAM_AKID }}
          PKR_VAR_SKEY: ${{ secrets.PACKER_IAM_SKEY }}
          PKR_VAR_azure_url: ${{ secrets.AZURE_URL }}
          PKR_VAR_azure_pat: ${{ secrets.AZURE_PAT }}
          PKR_VAR_azure_pool: ${{ secrets.AZURE_POOL }}
          PKR_VAR_S3_AKID: ${{ secrets.S3_IAM_AKID }}
          PKR_VAR_S3_SKEY: ${{ secrets.S3_IAM_SKEY }}
          PKR_VAR_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          PKR_VAR_UNREAL_ENGINE_VERSION: ${{ secrets.UNREAL_ENGINE_VERSION }}

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=cleanup"
          target: packer/packer.pkr.hcl
        working-directory: packer
        env:
          PACKER_LOG: 1
          PKR_VAR_aws_region: ${{ secrets.AWS_REGION }}
          PKR_VAR_vpc_id: ${{ secrets.VPC_ID }}
          PKR_VAR_subnet_id: ${{ secrets.SUBNET_ID }}
          PKR_VAR_AKID: ${{ secrets.PACKER_IAM_AKID }}
          PKR_VAR_SKEY: ${{ secrets.PACKER_IAM_SKEY }}
          PKR_VAR_azure_url: ${{ secrets.AZURE_URL }}
          PKR_VAR_azure_pat: ${{ secrets.AZURE_PAT }}
          PKR_VAR_azure_pool: ${{ secrets.AZURE_POOL }}
          PKR_VAR_S3_AKID: ${{ secrets.S3_IAM_AKID }}
          PKR_VAR_S3_SKEY: ${{ secrets.S3_IAM_SKEY }}
          PKR_VAR_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          PKR_VAR_UNREAL_ENGINE_VERSION: ${{ secrets.UNREAL_ENGINE_VERSION }}
          AWS_MAX_ATTEMPTS: 90
          AWS_POLL_DELAY_SECONDS: 60